-- AI Culture Builder Module - Database Migration
-- Run this to create the required tables for the Culture Builder feature

-- Table: appreciation_threads
-- Tracks weekly appreciation posts generated by AI
CREATE TABLE IF NOT EXISTS appreciation_threads (
  id BIGSERIAL PRIMARY KEY,
  generated_post_id BIGINT NOT NULL,
  week_start_date DATE NOT NULL,
  contributors_data JSONB NOT NULL,
  generation_status VARCHAR(50) NOT NULL DEFAULT 'generated',
  is_ai_generated BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_appreciation_post FOREIGN KEY (generated_post_id) 
    REFERENCES posts(id) ON DELETE CASCADE
);

-- Table: challenges
-- Stores community challenges created by AI
CREATE TABLE IF NOT EXISTS challenges (
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  challenge_type VARCHAR(50) NOT NULL,
  thread_id BIGINT,
  post_id BIGINT,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  participation_metrics JSONB,
  is_ai_generated BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_challenge_thread FOREIGN KEY (thread_id) 
    REFERENCES threads(id) ON DELETE SET NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_appreciation_threads_week 
  ON appreciation_threads(week_start_date DESC);

CREATE INDEX IF NOT EXISTS idx_appreciation_threads_status 
  ON appreciation_threads(generation_status);

CREATE INDEX IF NOT EXISTS idx_challenges_status 
  ON challenges(status);

CREATE INDEX IF NOT EXISTS idx_challenges_dates 
  ON challenges(start_date, end_date);

CREATE INDEX IF NOT EXISTS idx_challenges_type 
  ON challenges(challenge_type);

-- Comments for documentation
COMMENT ON TABLE appreciation_threads IS 'Tracks AI-generated weekly appreciation posts';
COMMENT ON TABLE challenges IS 'Stores community challenges created by the AI Culture Builder';

COMMENT ON COLUMN appreciation_threads.contributors_data IS 'JSONB snapshot of top contributors for the week';
COMMENT ON COLUMN challenges.challenge_type IS 'Type: knowledge-sharing, innovation, collaboration, wellness';

-- Grant permissions (adjust based on your database user)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON appreciation_threads TO your_app_user;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON challenges TO your_app_user;
-- GRANT USAGE, SELECT ON SEQUENCE appreciation_threads_id_seq TO your_app_user;
-- GRANT USAGE, SELECT ON SEQUENCE challenges_id_seq TO your_app_user;

-- Verification queries
-- SELECT 'appreciation_threads' as table_name, COUNT(*) as row_count FROM appreciation_threads
-- UNION ALL
-- SELECT 'challenges', COUNT(*) FROM challenges;
